/**
 * Free and consumer mailbox domains. People with these addresses are real contacts, but the
 * domain never identifies their company, so it must never become `companies.domain`.
 */
const FREE_MAIL_DOMAINS = new Set([
  "aol.com",
  "aim.com",
  "arcor.de",
  "att.net",
  "bellsouth.net",
  "bigpond.com",
  "bluewin.ch",
  "btinternet.com",
  "charter.net",
  "comcast.net",
  "cox.net",
  "email.com",
  "fastmail.com",
  "free.fr",
  "freenet.de",
  "gmail.com",
  "googlemail.com",
  "hanmail.net",
  "hey.com",
  "home.nl",
  "icloud.com",
  "inbox.com",
  "interia.pl",
  "kpnmail.nl",
  "laposte.net",
  "libero.it",
  "mac.com",
  "mail.com",
  "mail.ru",
  "mailbox.org",
  "me.com",
  "msn.com",
  "naver.com",
  "o2.pl",
  "onet.pl",
  "online.de",
  "optusnet.com.au",
  "orange.fr",
  "planet.nl",
  "pm.me",
  "posteo.de",
  "proton.me",
  "protonmail.com",
  "qq.com",
  "rediffmail.com",
  "rocketmail.com",
  "rogers.com",
  "sbcglobal.net",
  "seznam.cz",
  "sfr.fr",
  "shaw.ca",
  "skynet.be",
  "sky.com",
  "sympatico.ca",
  "t-online.de",
  "telenet.be",
  "tuta.io",
  "tutanota.com",
  "usa.com",
  "verizon.net",
  "virgilio.it",
  "virginmedia.com",
  "wanadoo.fr",
  "web.de",
  "wp.pl",
  "xtra.co.nz",
  "yandex.com",
  "yandex.ru",
  "ymail.com",
  "ziggo.nl",
  "zoho.com",
  "zohomail.com",
  "126.com",
  "163.com",
]);

/** Providers with many country variants (hotmail.co.uk, yahoo.de, gmx.at, live.fr, ...). */
const FREE_MAIL_FAMILIES = /^(hotmail|outlook|live|yahoo|gmx|aol)\.[a-z]{2,3}(\.[a-z]{2})?$/;

/** True for gmail.com, outlook.com, gmx.de and similar consumer mailbox domains. */
export function isFreeMailDomain(domain: string | null | undefined): boolean {
  if (!domain) return false;
  const value = domain.trim().toLowerCase();
  return FREE_MAIL_DOMAINS.has(value) || FREE_MAIL_FAMILIES.test(value);
}
