/**
 * A conservative, deterministic check for reply text that names a specific day or time:
 * weekday names, today and tomorrow, dates, clock times, and phrases that settle a meeting
 * ("see you", "invite for"). An automatic reply in a scheduling conversation may only point to
 * the booking link, so a match sends the draft to review; false positives only cost a review.
 * Covers English plus the day, month and phrase words of German, French, Spanish, Italian,
 * Dutch and Portuguese. Links are ignored (a booking link may contain numbers).
 */
import { withoutLinks } from "./link-match.js";

/** No letter or digit right before or after, so "sat" never matches inside "satisfied". */
const BEFORE = "(?<![\\p{L}\\p{N}])";
const AFTER = "(?![\\p{L}\\p{N}])";

/** Day names and relative days that also match with a suffix ("Tuesdays", "Dienstagnachmittag"). */
const DAY_STEMS = [
  "monday",
  "tuesday",
  "wednesday",
  "thursday",
  "friday",
  "saturday",
  "sunday",
  "today",
  "tonight",
  "tomorrow",
  "montag",
  "dienstag",
  "mittwoch",
  "donnerstag",
  "freitag",
  "samstag",
  "sonnabend",
  "sonntag",
  "heute",
  "übermorgen",
  "lundi",
  "mardi",
  "mercredi",
  "jeudi",
  "vendredi",
  "samedi",
  "dimanche",
  "aujourd['’]hui",
  "demain",
  "lunes",
  "martes",
  "miércoles",
  "miercoles",
  "jueves",
  "viernes",
  "sábado",
  "sabado",
  "domingo",
  "mañana",
  "manana",
  "lunedì",
  "lunedi",
  "martedì",
  "martedi",
  "mercoledì",
  "mercoledi",
  "giovedì",
  "giovedi",
  "venerdì",
  "venerdi",
  "sabato",
  "domenica",
  "domani",
  "stasera",
  "maandag",
  "dinsdag",
  "woensdag",
  "donderdag",
  "vrijdag",
  "zaterdag",
  "zondag",
  "vandaag",
  "overmorgen",
  "vanavond",
  "segunda-feira",
  "terça-feira",
  "terca-feira",
  "quarta-feira",
  "quinta-feira",
  "sexta-feira",
  "amanhã",
  "amanha",
];

/** Short words that only count as whole words. */
const DAY_WORDS = [
  "tue",
  "tues",
  "wed",
  "thu",
  "thur",
  "thurs",
  "fri",
  "sat",
  "sun",
  "hoy",
  "oggi",
  "hoje",
];

const MONTHS = [
  "january",
  "february",
  "march",
  "april",
  "may",
  "june",
  "july",
  "august",
  "september",
  "october",
  "november",
  "december",
  "jan",
  "feb",
  "mar",
  "apr",
  "jun",
  "jul",
  "aug",
  "sep",
  "sept",
  "oct",
  "nov",
  "dec",
  "januar",
  "februar",
  "märz",
  "maerz",
  "mai",
  "juni",
  "juli",
  "oktober",
  "dezember",
  "janvier",
  "février",
  "fevrier",
  "mars",
  "avril",
  "juin",
  "juillet",
  "août",
  "aout",
  "septembre",
  "octobre",
  "novembre",
  "décembre",
  "decembre",
  "enero",
  "febrero",
  "marzo",
  "abril",
  "mayo",
  "junio",
  "julio",
  "agosto",
  "septiembre",
  "setiembre",
  "octubre",
  "noviembre",
  "diciembre",
  "gennaio",
  "febbraio",
  "aprile",
  "maggio",
  "giugno",
  "luglio",
  "settembre",
  "ottobre",
  "dicembre",
  "januari",
  "februari",
  "maart",
  "mei",
  "augustus",
  "janeiro",
  "fevereiro",
  "março",
  "marco",
  "maio",
  "junho",
  "julho",
  "setembro",
  "outubro",
  "novembro",
  "dezembro",
].join("|");

/** Phrases that settle or announce a meeting at a time. */
const PHRASES = [
  "see you",
  "talk (?:to you )?then",
  "speak (?:to you )?then",
  "invit(?:e|es|ed|ing|ation|ations)",
  "pencil(?:l)?ed",
  "bis dann",
  "einladung",
  "nos vemos",
  "invitación",
  "invitacion",
  "ci vediamo",
  "invito",
  "tot dan",
  "uitnodiging",
  "até lá",
  "ate la",
  "convite",
];

const PATTERNS: RegExp[] = [
  // Day names and relative days (not the greeting "Guten Morgen").
  new RegExp(`${BEFORE}(?:${DAY_STEMS.join("|")})`, "iu"),
  new RegExp(`${BEFORE}(?:${DAY_WORDS.join("|")})\\.?${AFTER}`, "iu"),
  new RegExp(`${BEFORE}(?<!guten\\s)morgen`, "iu"),
  // Clock times: 10:00, 3pm, 3 p.m., 15 Uhr, 15h, 15h30, noon.
  /(?<!\d)\d{1,2}:\d{2}(?!\d)/u,
  new RegExp(`(?<!\\d)\\d{1,2}(?:[.:]\\d{2})?\\s?(?:am|pm|a\\.m\\.|p\\.m\\.)${AFTER}`, "iu"),
  new RegExp(`(?<!\\d)\\d{1,2}(?:[.:]\\d{2})?\\s?(?:uhr|h)(?:\\d{2})?${AFTER}`, "iu"),
  new RegExp(
    `${BEFORE}(?:noon|midday|midnight|o['’]clock|mittag|midi|mediodía|mezzogiorno)${AFTER}`,
    "iu",
  ),
  // "at 3" as a time ("at 3?", "at 3 then"), not an amount ("at 49 EUR", "at 3 locations").
  new RegExp(
    `${BEFORE}(?:at|um|à|om|alle|às|a las|a la)\\s+\\d{1,2}(?!\\d)(?=\\s*(?:$|[.,;:!?)]|(?:then|sharp|ish)${AFTER}))`,
    "iu",
  ),
  // Dates: 2026-10-08, 8.10., 10/8/2026, the 8th, Oct 8, 8 October, 8 de octubre.
  /(?<!\d)\d{4}-\d{1,2}-\d{1,2}(?!\d)/u,
  /(?<![\d.,])\d{1,2}[./]\d{1,2}(?:[./]\d{2,4})?(?!\d)/u,
  new RegExp(`(?<!\\d)\\d{1,2}(?:st|nd|rd|th)${AFTER}`, "iu"),
  new RegExp(`${BEFORE}(?:${MONTHS})\\.?\\s+\\d{1,2}(?!\\d)`, "iu"),
  new RegExp(
    `(?<!\\d)\\d{1,2}(?:st|nd|rd|th|\\.|er|º|°)?\\s+(?:de\\s+|of\\s+)?(?:${MONTHS})${AFTER}`,
    "iu",
  ),
  new RegExp(`${BEFORE}(?:${PHRASES.join("|")})${AFTER}`, "iu"),
];

/** Whether the text names a specific day or time, or settles a meeting (see module doc). */
export function namesMeetingTime(text: string): boolean {
  const plain = withoutLinks(text);
  return PATTERNS.some((pattern) => pattern.test(plain));
}
