/**
 * Reference docs generated from the registry (docs/reference/*): MCP tools, CLI, REST API and
 * the OpenAPI document. Output is deterministic for a given registry and version.
 */

import type { Registry } from "../core/engine.js";
import { TOOLSETS } from "../core/enums.js";
import { RESERVED_INPUT_FIELDS } from "../core/operation.js";
import { type FieldInfo, fieldsOf } from "../http/coerce.js";
import { buildOpenApi } from "../http/openapi.js";
import { buildCatalog, type Catalog, type OperationInfo } from "../mcp/catalog.js";
import { buildToolSpecs, type McpToolSpec } from "../mcp/tools.js";
import { exampleLine, flagName } from "./operation-commands.js";

const TOOLSET_NOTES: Record<string, string> = {
  core: "Default. The golden workflow from setup to daily review.",
  leads: "Lists, enrichment, suppressions and saved searches.",
  campaigns: "No built-in tools (manage_messages is in core); kept for custom modules.",
  inbox: "No built-in tools (manage_tasks is in core); kept for custom modules.",
  signals: "Automation rules.",
  content: "LinkedIn posts.",
  admin: "Workspaces, providers, webhooks, notifications, report schedules.",
  agent_brain: "Added automatically when a workspace uses the agent brain.",
};

function generatedNote(version: string, what: string): string {
  return `Generated by \`pnpm generate:reference\` from the operation registry (OpenOutbound ${version}). Do not edit by hand; ${what}`;
}

function byId<T extends { id: string }>(a: T, b: T): number {
  return a.id < b.id ? -1 : a.id > b.id ? 1 : 0;
}

function cell(text: string | undefined): string {
  return (text ?? "").replace(/\s+/g, " ").replaceAll("|", "\\|").trim();
}

function typeLabel(field: FieldInfo): string {
  if (field.enum) return field.enum.map((value) => `\`${value}\``).join(" \\| ");
  if (field.kind === "array") return `${field.itemKind ?? "any"}[]`;
  if (field.kind === "any") return "json";
  return field.kind;
}

/** docs/reference/mcp-tools.md */
export function renderMcpToolsReference(catalog: Catalog): string {
  const lines = [
    "# MCP tools",
    "",
    generatedNote(catalog.version, "edit the tool and operation definitions instead."),
    "",
    "Select toolsets with `openoutbound mcp --toolsets core,leads` (or `OPENOUTBOUND_MCP_TOOLSETS`, or `/mcp?toolsets=` over HTTP). `all` selects every toolset. Composite tools take an `action` plus the fields of that action. Every call also accepts `workspace`, `reason` and `idempotency_key` (not repeated below); read actions accept `response_format` and spend or send actions accept `dry_run`.",
    "",
  ];
  const operations = new Map(catalog.operations.map((op) => [op.id, op]));
  for (const toolset of TOOLSETS) {
    const { specs } = buildToolSpecs(catalog, new Set([toolset]));
    const tools = [...specs].sort((a, b) => (a.name < b.name ? -1 : a.name > b.name ? 1 : 0));
    lines.push(`## Toolset \`${toolset}\``, "", TOOLSET_NOTES[toolset] ?? "", "");
    if (tools.length === 0) {
      lines.push("No tools in this build.", "");
      continue;
    }
    for (const tool of tools) lines.push(...renderTool(tool, operations));
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

function renderTool(tool: McpToolSpec, operations: Map<string, OperationInfo>): string[] {
  const hints = tool.annotations;
  const flags = [
    hints.readOnlyHint ? "read-only" : null,
    hints.destructiveHint ? "destructive" : null,
    hints.idempotentHint ? "idempotent" : null,
    hints.openWorldHint ? "open world" : null,
  ].filter(Boolean);
  const lines = [`### \`${tool.name}\`: ${tool.title}`, "", tool.description.trim(), ""];
  lines.push(`Annotations: ${flags.length > 0 ? flags.join(", ") : "none"}.`, "");
  if (tool.actions) {
    lines.push("| Action | Operation | Effect | Summary |", "| --- | --- | --- | --- |");
    for (const [action, operation] of Object.entries(tool.actions)) {
      const known = operations.get(operation.id) ?? operation;
      lines.push(`| \`${action}\` | \`${known.id}\` | ${known.effect} | ${cell(known.summary)} |`);
    }
  } else if (tool.operation) {
    const known = operations.get(tool.operation.id) ?? tool.operation;
    lines.push(`Operation: \`${known.id}\` (${known.effect}): ${cell(known.summary)}.`);
  }
  const fields = fieldsOf(tool.inputSchema).filter(
    (field) => field.name !== "action" && !ALWAYS_ACCEPTED.has(field.name),
  );
  if (fields.length > 0) {
    lines.push("", "| Field | Type | Required | Description |", "| --- | --- | --- | --- |");
    for (const field of fields) {
      lines.push(
        `| \`${field.name}\` | ${typeLabel(field)} | ${field.required ? "yes" : "no"} | ${cell(field.description)} |`,
      );
    }
  }
  lines.push("");
  return lines;
}

/** Fields every tool accepts: the page says so once instead of repeating them per tool. */
const ALWAYS_ACCEPTED = new Set(["workspace", "reason", "idempotency_key"]);

const BUILTINS: Array<[string, string]> = [
  [
    "init [--home <dir>]",
    "Write .env (secret key, PGlite database, base URL) without overwriting values, create the database and a `default` workspace, print next steps.",
  ],
  [
    "doctor [--json] [--workspace <slug>]",
    "Check Node.js, engine home, config, base URL, secret key, database and migrations, workspaces, providers per slot, mailbox DNS and sending readiness (each workspace in one line, or the one given with `--workspace` in detail). Goes through a running `serve` when it owns the PGlite database. Exit 1 on FAIL.",
  ],
  [
    "serve [--port] [--host] [--no-worker] [--cors-origin <origin...>] [--rate-limit <n>]",
    "Run the HTTP server (REST, OpenAPI, /mcp, module routes) and the worker. Writes `.openoutbound/server.json` while running.",
  ],
  ["worker", "Run only the worker (jobs and schedules)."],
  [
    "mcp [--home <dir>] [--url] [--api-key] [--workspace] [--toolsets]",
    "MCP over stdio. Embedded (engine and worker in this process) or bridge to a running server (automatic when a local server owns the PGlite database).",
  ],
  [
    "sandbox",
    "Create (or fill in) the sandbox workspaces northwind and brightsmile (runs `sandbox seed`).",
  ],
  ["db migrate", "Apply pending database migrations."],
  [
    "db reencrypt-secrets",
    "After a secret key rotation, re-encrypt every stored secret with the current `OPENOUTBOUND_SECRET_KEY` (see the security guide).",
  ],
  ["openapi [--out <file>]", "Print or write the OpenAPI 3.1 document."],
  ["version", "Print the version."],
];

/** docs/reference/cli.md */
export function renderCliReference(catalog: Catalog): string {
  const lines = [
    "# CLI",
    "",
    generatedNote(catalog.version, "edit the operation definitions instead."),
    "",
    "## Global options",
    "",
    'Global options go before the command: `openoutbound --url http://127.0.0.1:7331 leads search --query "vp operations"`. Operation commands also accept them after the command, and every command accepts `--home` after it.',
    "",
    "| Option | Description |",
    "| --- | --- |",
    "| `--home <dir>` | Engine home with `.env` and `.openoutbound/` (env `OPENOUTBOUND_HOME`). Default: the current directory when it has them, else the package folder when it has them, else the current directory. |",
    "| `--workspace <id\\|slug>` | Workspace for operation commands (env `OPENOUTBOUND_WORKSPACE`). |",
    "| `--url <url>` | Call a running server instead of opening the database (bridge mode, env `OPENOUTBOUND_URL`). |",
    "| `--api-key <key>` | API key for bridge mode (env `OPENOUTBOUND_API_KEY`). |",
    "| `--json` | Print raw JSON on stdout. |",
    "| `--dry-run` / `--no-dry-run` | Preview only, or apply operations that preview by default. |",
    "| `--reason <text>` | Why, in one sentence (audit log). |",
    "| `--idempotency-key <key>` | Makes retries safe. |",
    "",
    "Operation commands take `--input <json|@file.json>` for the whole input (flags override its fields). Arrays accept repeated flags or comma lists, objects accept JSON or `@file.json`, booleans are `--flag` / `--no-flag`. Data goes to stdout, messages and hints to stderr. Exit codes: 0 ok, 1 error (also a mailbox login test that failed in `mailboxes test` or `mailboxes add --test`, after printing the result), 2 validation or usage error.",
    "",
    "## Built-in commands",
    "",
    "| Command | Description |",
    "| --- | --- |",
    ...BUILTINS.map(
      ([command, description]) => `| \`openoutbound ${cell(command)}\` | ${cell(description)} |`,
    ),
    "",
    "## Operation commands",
    "",
  ];
  const groups = new Map<string, OperationInfo[]>();
  for (const operation of [...catalog.operations].sort(byId)) {
    const group = operation.cli[0] ?? operation.id;
    groups.set(group, [...(groups.get(group) ?? []), operation]);
  }
  for (const group of [...groups.keys()].sort()) {
    lines.push(`### ${group}`, "");
    for (const operation of groups.get(group) ?? []) {
      lines.push(`#### \`openoutbound ${operation.cli.join(" ")}\``, "");
      lines.push(
        `${operation.summary}. Effect: ${operation.effect}. Operation: \`${operation.id}\`.`,
        "",
      );
      lines.push(operation.description.trim(), "");
      const fields = fieldsOf(operation.input_schema).filter(
        (field) =>
          field.name === "response_format" ||
          !(RESERVED_INPUT_FIELDS as readonly string[]).includes(field.name),
      );
      if (fields.length > 0) {
        lines.push("| Flag | Type | Required | Description |", "| --- | --- | --- | --- |");
        for (const field of fields) {
          const flag =
            field.kind === "boolean"
              ? `--${flagName(field.name)}` + ` / --no-${flagName(field.name)}`
              : `--${flagName(field.name)}`;
          lines.push(
            `| \`${flag}\` | ${typeLabel(field)} | ${field.required ? "yes" : "no"} | ${cell(field.description)} |`,
          );
        }
        lines.push("");
      }
      const example = operation.examples[0];
      if (example) {
        // A field named input takes the --input flag, so such examples use one flag per field.
        const usage = fields.some((field) => field.name === "input")
          ? exampleLine(operation)
          : `--input '${JSON.stringify(example.input)}'`;
        lines.push(`Example (${example.title}): \`${usage}\``, "");
      }
    }
  }
  return `${lines.join("\n").trimEnd()}\n`;
}

/** docs/reference/rest-api.md */
export function renderRestReference(catalog: Catalog): string {
  const lines = [
    "# REST API",
    "",
    generatedNote(catalog.version, "the full schema is in [openapi.json](./openapi.json)."),
    "",
    "## Basics",
    "",
    "- Base URL: `OPENOUTBOUND_BASE_URL` (default `http://localhost:7331`). Start the server with `openoutbound serve`.",
    "- Auth: `Authorization: Bearer oo_...` on `/v1/*` and `/mcp`. Create keys with `openoutbound keys create`.",
    "- Workspace: from a workspace key, or the `OpenOutbound-Workspace` header (id or slug) with instance keys. `OpenOutbound-Bind-Workspace` binds the key to one workspace for the request: other workspaces and instance-level operations answer 403 `forbidden`.",
    "- Idempotency: `Idempotency-Key` header (or `idempotency_key` in the body). Same key and body return the first result for 24 hours; a different body returns 409 `idempotency_mismatch`.",
    "- Errors: RFC 9457 `application/problem+json` with `code`, `detail`, `hint` and `details` (field issues). Validation errors are 422, bodies that are not JSON are 400.",
    "- Rate limit: 600 requests per minute per key by default (429 with `Retry-After`). Request ids: `X-Request-Id` (sent or generated). Body limit: 10 MB.",
    '- Results: work that waits for a human returns 202 with `{ status: "awaiting_approval", approval_id, summary }`; background work returns 202 with `{ job_id, status }`; dry runs return `{ dry_run: true, preview, warnings }`.',
    "",
    "## Generic routes",
    "",
    "| Method | Path | Description |",
    "| --- | --- | --- |",
    "| GET | `/health` | Health check (no auth). |",
    "| GET | `/openapi.json` | OpenAPI 3.1 document (no auth). |",
    "| GET | `/v1/ops` | Registry listing: operations with input JSON Schemas, and MCP tools. |",
    "| POST | `/v1/ops/{operation_id}` | Run any operation: the JSON body is its input. |",
    "| GET, POST, DELETE | `/mcp` | MCP over Streamable HTTP (stateless). `?toolsets=core,leads` selects toolsets. |",
    "",
    "## Operations",
    "",
  ];
  const groups = new Map<string, OperationInfo[]>();
  for (const operation of [...catalog.operations].sort(byId)) {
    const group = operation.id.split(".")[0] as string;
    groups.set(group, [...(groups.get(group) ?? []), operation]);
  }
  for (const group of [...groups.keys()].sort()) {
    lines.push(
      `### ${group}`,
      "",
      "| Method | Path | Operation | Effect | Scopes | Summary |",
      "| --- | --- | --- | --- | --- | --- |",
    );
    for (const operation of groups.get(group) ?? []) {
      const method = operation.http?.method ?? "POST";
      const path = operation.http?.path ?? `/v1/ops/${operation.id}`;
      lines.push(
        `| ${method} | \`${path}\` | \`${operation.id}\` | ${operation.effect} | ${operation.scopes.join(", ")} | ${cell(operation.summary)} |`,
      );
    }
    lines.push("");
  }
  if (groups.size === 0) lines.push("No operations in this build.", "");
  lines.push(
    "Every operation is also reachable as `POST /v1/ops/{operation_id}`. Path parameters (`:name`) and query parameters map to input fields of the same name; query values are converted to the field type (numbers, booleans, repeated or comma-separated arrays, JSON objects).",
    "",
  );
  return `${lines.join("\n").trimEnd()}\n`;
}

/** Every reference file, keyed by path relative to docs/reference/. */
export function renderReference(registry: Registry, version: string): Record<string, string> {
  const catalog = buildCatalog(registry, version);
  const openapi = buildOpenApi(registry, { serverUrl: "http://localhost:7331", version });
  return {
    "mcp-tools.md": renderMcpToolsReference(catalog),
    "cli.md": renderCliReference(catalog),
    "rest-api.md": renderRestReference(catalog),
    "openapi.json": `${JSON.stringify(openapi, null, 2)}\n`,
  };
}
